# Generated by Django 5.2.2 on 2025-06-06 19:22

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='abstractuser',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
